# VPS服务端配置文件示例

# 主服务端配置
server:
  host: "0.0.0.0"
  port: 8080
  mode: "release"  # debug or release
  cert_file: ""    # SSL证书文件路径（可选）
  key_file: ""     # SSL私钥文件路径（可选）

# 第二个服务端配置（可选）
# 当启用时，主服务端会将请求转发到第二个服务端
second_server:
  enabled: true   # 是否启用第二个服务端
  host: "206.190.238.198"  # 第二个服务端地址
  port: 8388       # 第二个服务端端口
  method: "aes-256-gcm"  # 加密方法
  password: "13687401432Fan!"  # 第二个服务端密码
  timeout: 300     # 超时时间(秒)

# Shadowsocks配置
shadowsocks:
  enabled: true
  method: "aes-256-gcm"  # 加密方法: aes-256-gcm, chacha20-poly1305, etc.
  password: "13687401432Fan!"
  port: 8389
  timeout: 300
  # 连接监控设置
  connection_monitoring:
    enabled: true
    log_failed_connections: true
    log_successful_connections: false
    max_connection_retries: 3
    connection_timeout_seconds: 60

# 日志配置
log:
  level: "info"  # 日志级别: debug, info, warn, error
  file: ""       # 日志文件路径，留空输出到控制台 