# VPS VPN Service 配置文件示例
# 复制此文件为 config.yaml 并根据需要修改

server:
  # HTTP服务器端口
  port: 8080
  # 服务器监听地址
  host: "0.0.0.0"
  # 运行模式: debug 或 release
  mode: "debug"
  # SSL证书文件路径（可选）
  cert_file: ""
  # SSL私钥文件路径（可选）
  key_file: ""

shadowsocks:
  # 是否启用Shadowsocks服务
  enabled: true
  # 加密方法: aes-256-gcm, chacha20-poly1305, aes-128-gcm, aes-192-gcm
  method: "aes-256-gcm"
  # 密码（请修改为强密码）
  password: "your-secure-password-here"
  # Shadowsocks服务端口
  port: 8388
  # 连接超时时间（秒）
  timeout: 300
  # 连接监控设置
  connection_monitoring:
    # 是否启用连接监控
    enabled: true
    # 是否记录失败的连接
    log_failed_connections: true
    # 是否记录成功的连接
    log_successful_connections: false
    # 最大连接重试次数
    max_connection_retries: 3
    # 连接超时时间（秒）
    connection_timeout_seconds: 60

log:
  # 日志级别: debug, info, warn, error
  level: "info"
  # 日志文件路径（留空则输出到控制台）
  file: "" 