version: '3.8'

services:
  vps-vpn:
    build: .
    container_name: vps-vpn
    ports:
      - "8080:8080"  # HTTP API端口
      - "8388:8388"  # Shadowsocks端口
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./logs:/app/logs
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    networks:
      - vps-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  vps-network:
    driver: bridge 